language: haskell

git:
  depth: 5

matrix:
  include:
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5
install:
  - ghc --version
  - cabal --version
  - cabal update
  - cabal install HUnit
script:
  - cd lab1
  - ghc *
  - ./Lab1Tests
  - cd ../lab2
  - ghc *
  - ./Lab2Tests
  - cd ../lab3
  - ghc *
  - ./Lab3Tests
  - cd ../lab4
  - ghc *
  - ./Lab4Tests
  - cd ../project
  - ghc *
  - ./Main
notifications:
  email: false
